version: '3'
services:

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9898:9090
    profiles:
      - infra
      - all
  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    volumes:
      - ./grafana/dashboards/main.json:/var/lib/grafana/dashboards/main.json
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3080:3000
    profiles:
      - infra
      - all

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831
      - 16686:16686
      - 14250:14250
    profiles:
      - infra
      - all

  otelp:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-collector/config.yaml:/etc/collector-gateway.yaml
      - logs:/tmp/
    command: [ "--config=/etc/collector-gateway.yaml" ]
    depends_on:
      - jaeger
    ports:
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
    profiles:
      - infra
      - all

  application:
    image: vovchello/quarkus-otel:latest
    depends_on:
      - redis
    environment:
      - QUARKUS_LOG_FILE_PATH=/tmp/application.log
    volumes:
      - logs:/tmp/
    ports:
      - 9090:9090
    profiles:
      - all

  order-manager:
    image: vovchello/order-manager
    depends_on:
      - redis
    profiles:
      - all

volumes:
  logs:
