{
 "title": "Application",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "traceId", "label": "traceId" }
  ]
 },
 "panels": [
  {
   "title": "order pressure",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "order_pressure{otel_scope_name=\"order_manager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} |= `ERROR` |= `${traceId}` | json | line_format `{{.attributes_mdc_traceId}} {{.attributes_message}}`"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} |= `${traceId}` | json | label_format level=attributes_level | label_format spanId=mdc_spanId | line_format `{{.body}}` | json | line_format `{{.loggerName}} {{.message}}`"
    }
   ]
  }
 ]
}